[tool.briefcase]
project_name = "AudioProj"
bundle = "com.example"
version = "0.0.1"
url = "https://google.com"
license = "MIT license"
author = 'W'
author_email = "W"

[tool.briefcase.app.audioproj]
formal_name = "AudioProj"
description = "Audio Proj"
icon = "src/audioproj/resources/audioproj"
sources = ['src/audioproj']
requires = []


[tool.briefcase.app.audioproj.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.audioproj.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.audioproj.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.audioproj.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.audioproj.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
